### ISSUE TITLE
Checklist link broken

### ISSUE THREAD

**Issue by shawnthompson** [w3c/fast#4]
The checklist link in the follow paragraph is broken. 

> This document is accompanied by a **[checklist](https://w3c.github.io/fast/checklist.html)** which is more complete and usable for groups evaluating technologies at this time.

It looks like the file isn't being deployed to the [gh-pages](https://github.com/w3c/fast/tree/gh-pages) branch.

**Comment by michael-n-cooper** [comment]
fixed by 69ee69bcb3004cce4f2bb5802e8897455665eda3
